#!/usr/bin/env python3
"""
run_all.py --- one-command reproduce for every TN0484 manuscript figure.

Runs each data producer (writes .npz) and then each figure generator, in
dependency order, writing all figures to ../figures/ (override with TN_FIGDIR
or --figdir). Each step runs in its own subprocess so one failure does not
abort the rest; a summary table is printed at the end.

Usage:
    python run_all.py                 # full reproduce -> ../figures/
    python run_all.py --figdir /tmp/f # dry-run into a scratch dir (figures/ untouched)
    python run_all.py --only fig_jcurve,fig_khz   # subset by figure name
    python run_all.py --list          # print the figure->script map and exit

Notes / known reproducibility gaps (see README.md "Figure -> script table"):
  * fig_lanmm_setup  -- hand-drawn schematic, not generated by any script.
  * fig_lanmm_arnold_p1/p2 -- need the external module lanmmv11 (from the LaNMM
    predictive-coding repo); skipped automatically if it is not importable.
  * fig_nmm2_jcurve  -- data is committed (nmm2_jcurve.npz) but the PLOTTER is
    missing; listed here as a gap until a plotter is added.
  * fig_entrainment  -- neither plotter nor data committed; full gap.

This script is heavy (long lock-in sweeps, parameter grids) and OVERWRITES the
committed figures when run with the default --figdir. Use --figdir to preview.
"""
import argparse
import importlib.util
import os
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_FIGDIR = os.path.join(HERE, "..", "figures")

# (label, script, args, [figures produced], note). Order = dependency order:
# data producers (.npz) first, then the generators that consume them.
STEPS = [
    # --- data producers (no figure output; write .npz consumed downstream) ---
    ("data: analyses_v2",   "analyses_v2.py",   [],        [], "-> analyses_v2.npz (feeds figures_v2)"),
    ("data: run_jcurve",    "run_jcurve.py",    [],        [], "-> jcurve_main.npz (feeds make_jfig)"),
    ("data: run_res",       "run_res.py",       [],        [], "-> jcurve_res.npz  (feeds make_jfig)"),
    ("data: qif_raster",    "qif_raster.py",    [],        [], "-> qif_raster.npz  (feeds make_qif_figs)"),
    ("data: nmm2_jc",       "nmm2_jc.py",       [],        [], "-> nmm2_jcurve.npz (for fig_nmm2_jcurve, plotter TBD)"),

    # --- figure generators (write to FIGDIR) ---
    ("figures_v2",  "figures_v2.py", [], [
        "fig_concept", "fig_bifurcation_sigmoid", "fig_resonance_map",
        "fig_carrier_independence", "fig_operating_point"], "needs analyses_v2.npz"),
    ("make_figures",     "make_figures.py",    [], ["fig_demodulation", "fig_verification"], ""),
    ("rerun_resonance",  "rerun_resonance.py", ["stable"], ["fig_resonance"],
        "stable branch; long lock-in (slow)"),
    ("rerun_resonance",  "rerun_resonance.py", ["cycle"],  [], "cycle branch"),
    ("rerun_resonance",  "rerun_resonance.py", ["plot"],   [], "writes fig_resonance"),
    ("khz_analysis",     "khz_analysis.py",    [], ["fig_khz"], "membrane-filtered kHz roll-off"),
    ("khz_direct",       "khz_direct.py",      [], ["fig_khz_direct"], "scipy-free; imports timing_not_rate"),
    ("nmm2_ping",        "nmm2_ping.py",       [], ["fig_nmm2_map", "fig_nmm2_resonance"], "grid (slow)"),
    ("lanmm_resonance",  "lanmm_resonance.py", [], ["fig_lanmm_map", "fig_lanmm_resonance"], "grid (slow)"),
    ("lanmm_arnold",     "lanmm_arnold_tongues.py", [], ["fig_lanmm_arnold_p1", "fig_lanmm_arnold_p2"],
        "NEEDS external lanmmv11; auto-skipped if absent"),
    ("make_jfig",        "make_jfig.py",       [], ["fig_jcurve"], "needs jcurve_main/res.npz"),
    ("tacs_jsweep",      "tacs_jsweep.py",     [], ["fig_tacs_jcurve"], "pure numpy"),
    ("timing_not_rate",  "timing_not_rate.py", [], ["fig_timing_not_rate"], "self-plots + writes npz"),
    ("make_qif_figs",    "make_qif_figs.py",   [], ["fig_qif_raster", "fig_qif_timing"], "needs qif_raster.npz"),
]

# Figures with no producing script (documented gaps).
GAPS = {
    "fig_lanmm_setup":  "hand-drawn schematic (not generated)",
    "fig_nmm2_jcurve":  "data committed (nmm2_jcurve.npz); PLOTTER MISSING",
    "fig_entrainment":  "no plotter and no committed data (entrain*.npz)",
}


def has_lanmm():
    return importlib.util.find_spec("lanmmv11") is not None


def figure_map():
    rows = []
    for label, script, _a, figs, note in STEPS:
        for f in figs:
            rows.append((f, script, note))
    for f, note in GAPS.items():
        rows.append((f, "(none)", "GAP: " + note))
    return sorted(rows)


def main():
    ap = argparse.ArgumentParser(description="Reproduce all TN0484 figures.")
    ap.add_argument("--figdir", default=os.environ.get("TN_FIGDIR") or DEFAULT_FIGDIR,
                    help="output directory for figures (default ../figures)")
    ap.add_argument("--only", default="", help="comma-separated figure names to (re)build")
    ap.add_argument("--list", action="store_true", help="print figure->script map and exit")
    args = ap.parse_args()

    if args.list:
        print(f"{'figure':28s} {'script':24s} note")
        print("-" * 78)
        for f, s, n in figure_map():
            print(f"{f:28s} {s:24s} {n}")
        return 0

    figdir = os.path.abspath(args.figdir)
    os.makedirs(figdir, exist_ok=True)
    only = {x.strip() for x in args.only.split(",") if x.strip()}
    env = dict(os.environ, TN_FIGDIR=figdir)
    lanmm_ok = has_lanmm()

    print(f"Reproducing figures into: {figdir}")
    if only:
        print(f"Subset: {sorted(only)}")
    if not lanmm_ok:
        print("note: lanmmv11 not importable -> lanmm_arnold_tongues will be skipped.")
    print()

    results = []  # (label, status, secs)
    for label, script, sargs, figs, note in STEPS:
        if only and not (set(figs) & only):
            continue
        if script == "lanmm_arnold_tongues.py" and not lanmm_ok:
            results.append((label, "SKIP (no lanmmv11)", 0.0))
            continue
        cmd = [sys.executable, os.path.join(HERE, script), *sargs]
        tag = f"{label} ({script} {' '.join(sargs)})".strip()
        print(f">>> {tag}  {('-- ' + note) if note else ''}")
        t0 = time.time()
        proc = subprocess.run(cmd, cwd=HERE, env=env)
        dt = time.time() - t0
        status = "ok" if proc.returncode == 0 else f"FAILED (rc={proc.returncode})"
        results.append((tag, status, dt))
        print(f"    {status}  [{dt:.1f}s]\n")

    print("=" * 70)
    print("SUMMARY")
    for label, status, dt in results:
        print(f"  {status:22s} {dt:6.1f}s  {label}")
    if GAPS:
        print("\nKnown gaps (no producing script):")
        for f, n in GAPS.items():
            print(f"  - {f}: {n}")
    failed = [r for r in results if r[1].startswith("FAILED")]
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
